name: Deploy on push to production branch

on:
  push:
    branches:
      - prod

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code to build server
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1  # If needed, otherwise remove this line
